name: Checkbox Workflow
on:
  workflow_dispatch:
    inputs:
      checkboxOption:
        description: '一个复选框选项'
        required: false
        default: false
jobs:
  exampleJob:
    runs-on: ubuntu-latest
    steps:
      - name: 输出复选框状态
        run: |
          echo "复选框是否被勾选：${{ inputs.checkboxOption }}"
